export enum WeightCategory {
    ULTRA_LIGHT = 'ULTRA_LIGHT',
    LIGHT = 'LIGHT',
    MEDIUM = 'MEDIUM',
    HEAVY = 'HEAVY',
    EXTRA_HEAVY = 'EXTRA_HEAVY',
    FREIGHT = 'FREIGHT'
}

export enum ParcelStatus {
    PENDING = 'PENDING',
    DRIVER_ASSIGNED = 'DRIVER_ASSIGNED',
    PICKED_UP = 'PICKED_UP',
    IN_TRANSIT = 'IN_TRANSIT',
    OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
    DELIVERED = 'DELIVERED',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
    EXCEPTION = 'EXCEPTION'
}

export enum TrackingEventType {
    ORDER_CREATED = 'ORDER_CREATED',
    DRIVER_ASSIGNED = 'DRIVER_ASSIGNED',
    PICKED_UP = 'PICKED_UP',
    LOCATION_UPDATE = 'LOCATION_UPDATE',
    OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
    DELIVERED = 'DELIVERED',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
    EXCEPTION = 'EXCEPTION'
}